[package]
name = "shearslice_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.149"
colorous = {version = "1.0.16", default-features = false }
image = {version = "0.25.9", default-features = false, features = ["png"]}
serde = { version = "1.0.228", default-features = false, features = ["derive","alloc",] } # alloc is for no_std, derive is needed


[dev-dependencies]
rstest = "0.25.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"